#ifndef OPCODES_H_
#define OPCODES_H_

typedef enum OP {
    OP_CONSTANT,
    OP_CONSTANT_LONG,
    OP_ZERO, OP_ONE,

    OP_ADD_INT, OP_ADD_UINT, OP_ADD_DOUBLE,
    OP_SUBTRACT_INT, OP_SUBTRACT_UINT, OP_SUBTRACT_DOUBLE,
    OP_MULTIPLY_INT, OP_MULTIPLY_UINT, OP_MULTIPLY_DOUBLE,
    OP_DIVIDE_INT, OP_DIVIDE_UINT, OP_DIVIDE_DOUBLE,
    OP_NEGATE_INT, OP_NEGATE_DOUBLE,

    OP_INT_TO_UINT, OP_INT_TO_DOUBLE,
    OP_UINT_TO_INT, OP_UINT_TO_DOUBLE,
    OP_DOUBLE_TO_INT, OP_DOUBLE_TO_UINT,

    OP_NOT,
    OP_EQUAL_INT, OP_EQUAL_DOUBLE, OP_EQUAL_UINT,
    OP_LESS_INT, OP_LESS_DOUBLE, OP_LESS_UINT,
    OP_GREATER_INT, OP_GREATER_DOUBLE, OP_GREATER_UINT,

    OP_RETURN,
} OP; 

#endif